import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Revizo dokumentasjon — én autogenerert sidebar fra docs/.
 * Når DOCS_PUBLIC_ONLY=true bygges ikke docs/internt/, så de forsvinner automatisk fra sidebar.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
